kaizen/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kaizen.views.home', name='home'),
    # url(r'^kaizen/', include('kaizen.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('suggestionbox.urls', namespace='suggestionbox')),

)

suggestionbox/urls.py
from django.conf.urls import patterns, include, url
from suggestionbox import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<suggestion_id>\d+)/$', views.detail, name='detail'),
)

suggestionbox/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Suggestion(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=100)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.ForeignKey('Status')
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return self.title
        

class Status(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    
    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'statuses'

class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'categories'

class Comment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User)
    pub_date = models.DateTimeField(auto_now_add=True)
    sid = models.ForeignKey(Suggestion)

    def __unicode__(self):
        return self.comment[:50]

suggestionbox/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from suggestionbox.models import Suggestion, Comment, Status, Category

# view for our index
def index(request):
    suggestions = Suggestion.objects.all().order_by('-pub_date')

    context = {
        'suggestions': suggestions,
    }

    return render(request, 'suggestionbox/index.html', context)

@login_required
def detail(request, suggestion_id):
    suggestion = get_object_or_404(Suggestion, pk=suggestion_id)

    context = {
        'suggestion': suggestion,
    }

    return render(request, 'suggestionbox/detail.html', context)

kaizen/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}改善 (Kaizen!!){% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <!-- see http://netdna.bootstrapcdn.com/#bootswatch for some other "flavors" to try -->
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        
        <!-- Latest compiled and minified JavaScript -->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale: 1.0">
        <style type="text/css">
           body { padding-top: 70px; }
        </style>
        {% block extrascripts %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="navbar navbar-default navbar-fixed-top">
                <a class="navbar-brand" href="/">Django Is Awesome</a>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="/contact/">Contact Me</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="/admin/"><span class="glyphicon glyphicon-user"></span> Admin</a></li>
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
                </ul>
            </div>
            
            <div class="body-content">
                <div class="row">
                    <!-- main content area -->
                    <div class="col-lg-9">
                    {% block content %}
                    <div class="jumbotron">
                    <h1>Hello, World!</h1>
                    <p>Welcome to a world of Twitter Bootstrap CSS, making life easier for all of us.</p>
                    </div>
                    {% endblock %}
                    </div>
                    <!-- sidebar -->
                    <div class="col-lg-3">
                        <h3>Optional Sidebar</h3>
                        <ul>
                        <li>Item 1</li>
                        <li>Item 2</li>
                        <li>Item 3</li>
                        </ul>
                    </div>
                </div>

            </div><!-- body-content -->
            <hr>
            <footer>
                Copyright &copy;2013 Your Name. All rights reserved.
            </footer>
        </div><!-- container -->
    </body>
<html>

suggestionbox/templates/suggestionbox/detai.html
{% extends 'base.html' %}

{% block title %}改善 - Details for {{ suggestion.title }}{% endblock %}

{% block content %}

{% if suggestions %}
<h1>List of Suggestions</h1>



<table class="table">
<tr>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Pub Date</th>
    <th>Status</th>
    <th>Category</th>
</tr>
{% for suggestion in suggestions %}
<tr>
    <td>{{ suggestion.user }}</td>
    <td>{{ suggestion.title }}</td>
    <td>{{ suggestion.description }}</td>
    <td>{{ suggestion.pub_date }}</td>
    <td>{{ suggestion.status }}</td>
    <td>{{ suggestion.category }}</td>
</tr>

{{ suggestion.title }}

{% endfor %}
</table>

{% else %}
<h1>No Suggestions Yet</h1>
<p>Be the first of your friends to suggest something.</p>
{% endif %}

{% endblock %}

suggestionbox/templates/suggestionbox/detail.html
{% extends 'base.html' %}

{% block title %}改善 - Details for {{ suggestion.title }}{% endblock %}

{% block content %}

<h1>{{ suggestion.title }}</h1>

<p>{{ suggestion.description }}</p>

<table class="table">
<tr> <td>Suggested by:</td><td>{{ suggestion.user }}</td></tr>
    <tr><td>Published Date:</td><td>{{ suggestion.pub_date }}</td></tr>
    <tr><td>Status</td><td>{{ suggestion.status }}</td></tr>
    <tr><td>Category</td><td>{{ suggestion.category }}</td></tr>
</tr>
</table>

<p>-- comments go here --</p>


{% endblock %}

suggestionbox/templates/suggestionbox/index.html
{% extends 'base.html' %}

{% block title %}改善 - List of Suggestions{% endblock %}

{% block content %}

{% if suggestions %}
<h1>List of Suggestions</h1>



<table class="table">
<tr>
    <th>Author</th>
    <th>Title</th>
    <th>Description</th>
    <th>Pub Date</th>
    <th>Status</th>
    <th>Category</th>
</tr>
{% for suggestion in suggestions %}
<tr>
    <td>{{ suggestion.user }}</td>
    <td><a href="{% url 'suggestionbox:detail' suggestion.id %}">{{ suggestion.title }}</a></td>
    <td>{{ suggestion.description }}</td>
    <td>{{ suggestion.pub_date }}</td>
    <td>{{ suggestion.status }}</td>
    <td>{{ suggestion.category }}</td>
</tr>

{{ suggestion.title }}

{% endfor %}
</table>

{% else %}
<h1>No Suggestions Yet</h1>
<p>Be the first of your friends to suggest something.</p>
{% endif %}

{% endblock %}